name: Commands
version: '${project.version}'
main: me.ratio.commands.Commands
description: developed by billdims
commands:
  ping:
    description: Shows player's latency
  ratio:
    description: Fun command
  credits:
    aliases: [cr]
    description: Credits
  bc:
    aliases: [alert]
    description: Broadcasts a message
  logs:
    description: Player logs concept
  push:
    description: Push yourself
  book:
    description: You get to write anything you want in the book
  motd:
    description: Custom Server MOTD
  comver:
    description: Shows the Commands version